exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('secondaryPrograms').del()
    .then(function () {
      // Inserts seed entries
      return knex('secondaryPrograms').insert([
        {title: 'Catwalk for Cancer', description: 'Fashion show fundraiser that promotes youth and adult creativity while using it as a forum to discuss the importance for males and females to regularly have mammograms, statistics impacting those who are most vulnerable and the supports needed for those going through chemotherapy.', program_id: 4, grantor_id: 1},
        {title: 'Children Caring for Children (C3)', description: 'The program was to bring hope and hugs to those affected by the hurricanes in Puerto Rico. Care packages were made for the youth by the youth to show care and compassion and to teach about the impact of disasters and loss.', program_id: 4, grantor_id: 7},
        {title: 'College-Readiness', description: 'The six-week program in support with Jobs for America’s Graduates and IU School of Social Work begins to start the discussion with middle and high-schoolers about post High School graduation options. The programs integrates workshops around admissions, SMART goals and interests/hobbies.', program_id: 4, grantor_id: 6},
        {title: 'Community Events', description: 'Typically participants and their families partake in cause-oriented walks which include but are not limited to: American Diabetes Association, Susan G. Coleman, March of Dimes, American Cancer Society, American Heart Association etc.', program_id: 4},
        {title: 'Dance Out Diabetes', description: 'This initiative in collaboration with the American Diabetes Association and the National Diabetes Education Program call for youth and adult performers to come together to raise awareness and funds for combating diabetes. The event is also to provide an outing for caregivers of diabetics to relax and receive tools and resources to practice self-care while taking care of their loved ones. Those who have been diagnosed with diabetes are able to get resources, sign-up for additional supports and programs and discuss alternatives/substitutes for cooking.', program_id: 4, grantor_id: 1},
        {title: 'Dancing through the Decades', description: 'This program allows for the participants to learn about the evolution of dance from the 1970’s to present. The students learn about musicians, dance crazes, and genres popular during the timeframe being highlighted.', program_id: 4},
        {title: 'Diverse Dance', description: 'This program cultivates an environment where participants are able to learn an array of cultural dances and the differences and commonalities of music origination and how they influence one another. The dances of focuses are hip hop, African, Bhangra and Salsa.', program_id: 4, grantor_id: 1},
        {title: 'ExQuizIt Dance Team', description: 'This program provides a platform for youth that want to be physically active and/or want to be introduced into hip hop dance. The participants perform at a variety of community events. Through dance participants are able to become more confident regarding their self-awareness build their self-esteem, create new friendships and foster their creativity.', program_id: 4},
        {title: 'Hip Hop for Hunger', description: 'This initiative brings together the top talent of Marion County and doughnut counties to host a performing arts show while addressing the need for more resources within our communities to combat youth hunger. Donations collected are provided to a local food pantry to sustain the efforts of outreach for the community.', program_id: 4, grantor_id: 1},
        {title: 'Hips for Hunger and Health Fair', description: 'This initiative is to bring awareness to local youth hunger and the need to be physically, emotionally and spiritually healthy. Hips for Hunger and Health Fair is a combination of Zumba, Hip Hop Aerobics and Chair Aerobics instructors providing classes while both statewide and community organizations provide health screenings, program referrals, food demonstrations and giveaways. Donations received are provided to a local food pantry in order to continue sustainability of need within the catchment area.', program_id: 4, grantor_id: 2},
        {title: 'Hoops for Hunger', description: 'This initiative is hosted off the heels of March Madness and is for youth and adults. The bracket-inspired program allows for individuals and teams to come together to advocate for a need of more resources within the community to combat youth hunger. Donations collected are then given to a local food bank to assist in the sustainability of community outreach.', program_id: 4, grantor_id: 1},
        {title: 'Leadership Training', description: 'Youth-leaders of our program are enrolled in the Jefferson Awards Students in Action Youth Philanthropy program. They attend two conferences – one in the Fall and one in the Winter.', program_id: 4},
        {title: 'Majorette’n Out Obesity', description: 'This program highlights the importance of being active and staying active in order to combat youth obesity. The youth led program also provides tips and exercises for the participants to take-away to complete during the week to stay limber and ready for weekly practices. The end Majorette performance is completed at a local showcase.', program_id: 4, grantor_id: 1},
        {title: 'Media Smart Youth', description: 'This program utilizes the curriculum “Eat, Think, and Be Active" an interactive educational program that helps young people ages 11 to 13 understand the complex media world around them and how it can influence their health, especially in regard to nutrition and physical activity.', program_id: 4, grantor_id: 3},
        {title: 'Peace Begins with Me', description: 'This initiative is to spread kindness and peace throughout our communities through pledges and shirt branding.', program_id: 4, grantor_id: 8},
        {title: 'Ride’N Resposibly', description: 'This initiative highlights the importance of teen driving and the precautions needed before getting behind the wheel. The event is centered on a car show that is supported by local car clubs and educational information is provided by the Indiana Criminal Justice Institute Traffic Safety Division, local insurance companies and local driving schools.', program_id: 4, grantor_id: 5},
        {title: 'Scholarship Program', description: 'Open to Juniors and Seniors in high school. Criteria is primarily based on community engagement and volunteerism completed by the student. The award is given annually and ranges between $100-$200. Students are able to use the dollars for any expenses associated with post-high school graduation. The announcement and application are rolled out the spring of each year and are due by the end of May.', program_id: 3},
        {title: 'She Get it From Her Mama', description: 'This program is for young girls and their parent/guardians to spend quality time together, work on their communication, learn more about what is going on in their lives and strengthen their bonds. During the program the participants complete activities and learn a routine that they perform together at a local showcase.', program_id: 4, grantor_id: 1},
        {title: 'Strengthen My Swagg', description: 'This program uses the Six Pillars of Character Building curriculum as its foundation and integrates hands-on experience for the youth.', program_id: 4, grantor_id: 1},
        {title: 'Suicide Project', description: 'This program is done with high school students who are interested in learning the warning signs of someone who may be contemplating suicide. The youth co-facilitate this program with a Licensed Social Worker following a stringent curriculum.', program_id: 4, grantor_id: 1},
        {title: 'Tutoring and Talent', description: 'This program truly represents the mission of our organization where arts and academics are integrated. In conjunction with the ladies of America’s Next Top Role Models there is 30 minutes of tutoring before every dance class. Tutoring is available not only for participants of the dance program but their siblings as well.', program_id: 4, grantor_id: 1},
        {title: 'Youth and Yoga', description: 'This program is for both youth and adults to learn ways to integrate mindfulness into their daily living/schedule. Youth co-facilitate the program with a trained yoga instructor.', program_id: 4, grantor_id: 1},
        {title: 'Youth Health Summit', description: 'The annual event is in collaboration with the Office of Minority Health to address “hot topics” identified by youth. Some topics in the past have been teen dating, human trafficking, race relations and substance abuse. The event also has screenings available for youth and entities that specifically provide programming for youth in middle and high school.', program_id: 4, grantor_id: 1}
      ]);
    });
};
